%% Report §11.4: the documentation a compiled module carries, rendered as
%% CommonMark. `ernc --doc` writes a whole module page and the shell's
%% `:doc` one declaration of it (§11.2); both read the EEP 48 documentation
%% chunk of the `.erc` (§11.1), which is the only source: a page is never
%% rendered from a source file.
-module(ern_page).

-export([page/1, module_head/1, declaration/2, session_declaration/3, prelude_page/0,
         prelude_declaration/1, since/1]).

-include_lib("typer/include/ern_types.hrl").

%% Report §11.4: the page of one compiled module, built from its
%% documentation chunk and the namespace in its interface chunk (§11.1).
-spec page(binary() | file:filename()) -> iolist().
page(Beam) ->
    {ok, #{iface := #iface{namespace = Ns}}} = ern_emitter:read_interface(Beam),
    {ok, Docs} = ern_emitter:read_docs(Beam),
    render(["Ernest module ", qname(Ns)], qname(Ns) ++ ".", Docs).

%% Report §9, §11.4: the prelude's page, from the documentation its table
%% carries. A prelude name is written without a module's name before it.
-spec prelude_page() -> iolist().
prelude_page() ->
    render("Ernest prelude", "", ern_prelude:docs()).

%% Report §11.2: a module's documentation as `:doc` shows it, the head of
%% its page: the title, the version, and the module's doc block. What the
%% module declares is `:browse`'s to list.
-spec module_head(binary() | file:filename()) -> iolist().
module_head(Beam) ->
    {ok, #{iface := #iface{namespace = Ns}}} = ern_emitter:read_interface(Beam),
    {ok, {docs_v1, _, ernest, _, ModDoc, _, _}} = ern_emitter:read_docs(Beam),
    head(["Ernest module ", qname(Ns)], ModDoc).

render(Title, Prefix, {docs_v1, _, ernest, _, ModDoc, Meta, Entries}) ->
    [head(Title, ModDoc),
     [entry(E, Prefix) || E <- Entries],
     "---\n\nGenerated by ernc ", ?VERSION, " from ",
     unicode:characters_to_list(maps:get(source, Meta, <<>>)), ".\n"].

head(Title, ModDoc) ->
    ModText = case ModDoc of
                  none -> [];
                  #{<<"en">> := T} ->
                      {Text, Since} = split_since(T),
                      [since_line(Since), Text, "\n\n"]
              end,
    ["# ", Title, "\n\n", ModText].

entry({{_, Name, _}, _, Signature, Doc, Meta}, Prefix) ->
    section([Prefix, atom_to_list(Name)], Signature, Doc, Meta).

%% A declaration's section under its heading: its signature, its `since`
%% line, its text, and its items.
section(Heading, Signature, Doc, Meta) ->
    {Text, Since} = case Doc of
                        none -> {undefined, undefined};
                        #{<<"en">> := T} -> split_since(T)
                    end,
    ["## ", Heading, "\n\n```ernest\n",
     lists:join("\n", [binary_to_list(L) || L <- Signature]), "\n```\n\n",
     since_line(Since),
     case Text of
         T2 when T2 =:= undefined; T2 =:= <<>> -> [];
         _ -> [Text, "\n\n"]
     end,
     items(Meta)].

%% The documented constructors and fields as a list.
items(#{items := Items}) -> list([item(I) || I <- Items]);
items(_) -> [].

item(#{kind := constructor, name := N, doc := Doc, fields := Fields}) ->
    FieldItems = [["  - `", atom_to_list(F), " : ", T, "`: ", FDoc, "\n"]
                  || #{name := F, type := T, doc := FDoc} <- Fields, FDoc =/= none],
    case {Doc, FieldItems} of
        {none, []} -> [];
        {none, _} -> [["- `", atom_to_list(N), "`\n"], FieldItems];
        _ -> [["- `", atom_to_list(N), "`: ", Doc, "\n"], FieldItems]
    end.

list(Items) ->
    case lists:flatten(Items) of
        [] -> [];
        _ -> [Items, "\n"]
    end.

%% Appendix E.0 rule 6: a doc block's last line `since v` names the version
%% the declaration appeared in; it is rendered after the synopsis.
split_since(Doc) ->
    case re:run(Doc, "^(.*?)\\n?since ([0-9][0-9A-Za-z.+-]*)\\s*$",
                [dotall, {capture, all_but_first, binary}]) of
        {match, [Text, V]} -> {string:trim(Text, trailing), V};
        nomatch -> {Doc, undefined}
    end.

since_line(undefined) -> [];
since_line(V) -> ["*Since ", V, ".*\n\n"].

%% Report §11.2: one declaration's documentation, as `:doc` prints it. The
%% name is the unqualified one the entry carries, `map` or `Stack.push`, as
%% it is written, so that no name is made of what a person typed.
-spec declaration(binary() | file:filename(), binary()) -> {ok, iolist()} | none.
declaration(Beam, Name) ->
    {ok, #{iface := #iface{namespace = Ns}}} = ern_emitter:read_interface(Beam),
    {ok, {docs_v1, _, ernest, _, _, _, Entries}} = ern_emitter:read_docs(Beam),
    case find(Name, Entries) of
        {ok, E} -> {ok, entry(E, qname(Ns) ++ ".")};
        none -> none
    end.

%% The entry of a name as it is written.
find(Name, Entries) ->
    case [E || {{_, N, _}, _, _, _, _} = E <- Entries, atom_to_binary(N) =:= Name] of
        [E | _] -> {ok, E};
        [] -> none
    end.

%% Report §11.2: a declaration the session made, under the name the session
%% writes and with the signature given, the type as the shell prints it,
%% since a value's entry is written under the input's namespace, which is
%% not the session's; `entry` keeps the entry's own, which a type's is.
%% A name with no entry, one a `let` at the prompt bound, is its name and
%% type alone.
-spec session_declaration(binary() | none, binary(), [string()] | entry) -> iolist().
session_declaration(Beam, Name, Signature) ->
    Entries = case Beam of
                  none ->
                      [];
                  _ ->
                      {ok, {docs_v1, _, ernest, _, _, _, Es}} = ern_emitter:read_docs(Beam),
                      Es
              end,
    case find(Name, Entries) of
        none ->
            section(Name, lines(Signature), none, #{});
        {ok, E} when Signature =:= entry ->
            entry(E, "");
        {ok, {K, A, _, Doc, Meta}} ->
            entry({K, A, lines(Signature), Doc, Meta}, "")
    end.

lines(Signature) -> [unicode:characters_to_binary(L) || L <- Signature].

%% Report §9, §11.2: one prelude name's documentation, `send`,
%% `Address.call`, or `Optional`, as `:doc` prints it.
-spec prelude_declaration(binary()) -> {ok, iolist()} | none.
prelude_declaration(Name) ->
    {docs_v1, _, ernest, _, _, _, Entries} = ern_prelude:docs(),
    case find(Name, Entries) of
        {ok, E} -> {ok, entry(E, "")};
        none -> none
    end.

%% Appendix E.0 rule 6: the version a module, or the prelude, appeared in,
%% which a declaration without a `since` of its own shares.
-spec since(binary() | file:filename() | prelude) -> binary() | undefined.
since(prelude) ->
    module_since(ern_prelude:docs());
since(Beam) ->
    {ok, Docs} = ern_emitter:read_docs(Beam),
    module_since(Docs).

module_since({docs_v1, _, _, _, #{<<"en">> := T}, _, _}) -> element(2, split_since(T));
module_since(_) -> undefined.

qname(Ns) ->
    lists:flatten(lists:join(".", [atom_to_list(S) || S <- Ns])).
