%% Report §11.4: the documentation a compiled module carries, rendered as
%% CommonMark. `ernc --doc` writes a whole module page and the shell's
%% `:doc` one declaration of it (§11.2); both read the EEP 48 documentation
%% chunk of the `.erc` (§11.1), which is the only source: a page is never
%% rendered from a source file.
-module(ern_page).

-export([page/1, declaration/2, prelude_page/0, prelude_declaration/1, since/1]).

-include_lib("typer/include/ern_types.hrl").

%% Report §11.4: the page of one compiled module, built from its
%% documentation chunk and the namespace in its interface chunk (§11.1).
-spec page(binary() | file:filename()) -> iolist().
page(Beam) ->
    {ok, #{iface := #iface{namespace = Ns}}} = ern_emitter:read_interface(Beam),
    {ok, Docs} = ern_emitter:read_docs(Beam),
    render(["Ernest module ", qname(Ns)], qname(Ns) ++ ".", Docs).

%% Report §9, §11.4: the prelude's page, from the documentation its table
%% carries. A prelude name is written without a module's name before it.
-spec prelude_page() -> iolist().
prelude_page() ->
    render("Ernest prelude", "", ern_prelude:docs()).

render(Title, Prefix, {docs_v1, _, ernest, _, ModDoc, Meta, Entries}) ->
    ModText = case ModDoc of
                  none -> [];
                  #{<<"en">> := T} ->
                      {Text, Since} = split_since(T),
                      [since_line(Since), Text, "\n\n"]
              end,
    Members = member_docs(Entries),
    ["# ", Title, "\n\n", ModText,
     [entry(E, Prefix, Members) || E <- Entries],
     "---\n\nGenerated by ernc ", ?VERSION, " from ",
     unicode:characters_to_list(maps:get(source, Meta, <<>>)), ".\n"].

%% Appendix E.0 rule 6: a member of an abstract type is documented at its
%% signature entry, and the member's own declaration inherits that text.
member_docs(Entries) ->
    maps:from_list([{{TName, N}, Doc}
                    || {{type, TName, _}, _, _, _, #{items := Items}} <- Entries,
                       #{kind := signature, name := N, doc := Doc} <- Items,
                       Doc =/= none]).

entry({{_, Name, _}, _, Signature, Doc, Meta}, Prefix, Members) ->
    {Own, Since} = case Doc of
                       none -> {undefined, undefined};
                       #{<<"en">> := T} -> split_since(T)
                   end,
    %% a member whose own block is only its `since` line inherits the entry's text
    Text = case Own of
               T2 when T2 =:= undefined; T2 =:= <<>> ->
                   maps:get(member_key(Name), Members, undefined);
               _ -> Own
           end,
    ["## ", Prefix, atom_to_list(Name), "\n\n```ernest\n",
     lists:join("\n", [binary_to_list(L) || L <- Signature]), "\n```\n\n",
     since_line(Since),
     case Text of
         undefined -> [];
         _ -> [Text, "\n\n"]
     end,
     items(Meta)].

member_key(Name) ->
    case string:split(atom_to_list(Name), ".") of
        [Owner, Member] -> {list_to_atom(Owner), list_to_atom(Member)};
        _ -> none
    end.

%% The documented constructors, fields, and signature entries as a list.
items(#{items := Items}) -> list([item(I) || I <- Items]);
items(_) -> [].

item(#{kind := constructor, name := N, doc := Doc, fields := Fields}) ->
    FieldItems = [["  - `", atom_to_list(F), " : ", T, "`: ", FDoc, "\n"]
                  || #{name := F, type := T, doc := FDoc} <- Fields, FDoc =/= none],
    case {Doc, FieldItems} of
        {none, []} -> [];
        {none, _} -> [["- `", atom_to_list(N), "`\n"], FieldItems];
        _ -> [["- `", atom_to_list(N), "`: ", Doc, "\n"], FieldItems]
    end;
item(#{kind := signature, name := N, type := T, doc := Doc}) ->
    case Doc of
        none -> [];
        _ -> ["- `", atom_to_list(N), " : ", T, "`: ", Doc, "\n"]
    end.

list(Items) ->
    case lists:flatten(Items) of
        [] -> [];
        _ -> [Items, "\n"]
    end.

%% Appendix E.0 rule 6: a doc block's last line `since v` names the version
%% the declaration appeared in; it is rendered after the synopsis.
split_since(Doc) ->
    case re:run(Doc, "^(.*?)\\n?since ([0-9][0-9A-Za-z.+-]*)\\s*$",
                [dotall, {capture, all_but_first, binary}]) of
        {match, [Text, V]} -> {string:trim(Text, trailing), V};
        nomatch -> {Doc, undefined}
    end.

since_line(undefined) -> [];
since_line(V) -> ["*Since ", V, ".*\n\n"].

%% Report §11.2: one declaration's documentation, as `:doc` prints it. The
%% name is the unqualified one the entry carries, `map` or `Stack.push`.
-spec declaration(binary() | file:filename(), atom()) -> {ok, iolist()} | none.
declaration(Beam, Name) ->
    {ok, #{iface := #iface{namespace = Ns}}} = ern_emitter:read_interface(Beam),
    {ok, {docs_v1, _, ernest, _, _, _, Entries}} = ern_emitter:read_docs(Beam),
    case [E || {{_, N, _}, _, _, _, _} = E <- Entries, N =:= Name] of
        [] -> none;
        [E | _] -> {ok, entry(E, qname(Ns) ++ ".", member_docs(Entries))}
    end.

%% Report §9, §11.2: one prelude name's documentation, `send`,
%% `Address.call`, or `Optional`, as `:doc` prints it.
-spec prelude_declaration(atom()) -> {ok, iolist()} | none.
prelude_declaration(Name) ->
    {docs_v1, _, ernest, _, _, _, Entries} = ern_prelude:docs(),
    case [E || {{_, N, _}, _, _, _, _} = E <- Entries, N =:= Name] of
        [] -> none;
        [E | _] -> {ok, entry(E, "", #{})}
    end.

%% Appendix E.0 rule 6: the version a module, or the prelude, appeared in,
%% which a declaration without a `since` of its own shares.
-spec since(binary() | file:filename() | prelude) -> binary() | undefined.
since(prelude) ->
    module_since(ern_prelude:docs());
since(Beam) ->
    {ok, Docs} = ern_emitter:read_docs(Beam),
    module_since(Docs).

module_since({docs_v1, _, _, _, #{<<"en">> := T}, _, _}) -> element(2, split_since(T));
module_since(_) -> undefined.

qname(Ns) ->
    lists:flatten(lists:join(".", [atom_to_list(S) || S <- Ns])).
