%% Well-typed programs generated (plan, MVP 2.99c item 2): programs built by
%% type, so that each type-checks by construction, then checked, compiled,
%% loaded and run in this host through the runtime's entry, as the shell
%% runs its own. Four oracles: the checker accepts the program; the Erlang it
%% becomes compiles and loads; the run ends by returning, or by a cause of
%% report §7.4, or by a deadlock; and what it prints is what an interpreter
%% of the same program, written here in Erlang from the report's rules,
%% computes, so that a program compiled to the wrong value is a finding too.
%%
%% Two rounds. The pure programs: `let`, `if`, `match` over every pattern
%% form, constructors positional and named, records with selection and
%% update, tuples, lists, lambdas, helper functions, structural recursion,
%% and the operations of Int and String with a few of List and Optional;
%% each prints `Io.show` of its value. The processes, a few shapes around
%% the same expressions: a worker that sends its value back, a server that
%% answers a call, a receive that times out, and a receive that nothing
%% will answer, a deadlock.
%%
%% The seed is drawn afresh each run and named in a failure; ERN_SEED draws
%% the same programs again.
-module(ern_typed_programs_tests).

-include_lib("eunit/include/eunit.hrl").

-define(PURE, 400).
-define(PROCESSES, 60).
-define(MODULE_NAMESPACE, ['Generated']).

%% The declarations every program has, which the generator builds on.
-define(DECLARATIONS,
        "type Shape = Circle(Int) | Rect(w : Int, h : Int) | Dot\n\n"
        "type Point = Point(x : Int, y : Int)\n\n"
        "type Box(a) = Box(item : a)\n\n").

%%
%% The tests
%%

%% report §3, §4, §5, §7.4, Appendix E.1: every pure program generated by
%% type checks, compiles, runs and prints what the interpreter computes
pure_programs_test_() ->
    {timeout, 600, fun() -> generated(?PURE, fun pure_program/1) end}.

%% report §6, §6.6, §8.6: every program of the process shapes checks,
%% compiles, runs and prints what the interpreter computes, a deadlock
%% ending in the entry process's fault
process_programs_test_() ->
    {timeout, 600, fun() -> generated(?PROCESSES, fun process_program/1) end}.

%% Count programs from a fresh seed, or ERN_SEED's; the first that fails an
%% oracle, with the seed, its number and its text.
generated(Count, Program) ->
    Seed = case os:getenv("ERN_SEED") of
               false -> erlang:phash2({erlang:monotonic_time(), self()});
               Given -> list_to_integer(Given)
           end,
    rand:seed(exsss, Seed),
    ?assertEqual(none, first_failure(Count, Program, Seed, 1)).

first_failure(Count, _, _, Number) when Number > Count ->
    none;
first_failure(Count, Program, Seed, Number) ->
    put(fresh, 0),
    {Text, Expected} = Program(2 + Number * 4 div Count),
    case outcome(Text) of
        Expected -> first_failure(Count, Program, Seed, Number + 1);
        Got -> #{seed => Seed, program => Number, text => Text, expected => Expected, got => Got}
    end.

%% A program checked, compiled, loaded and run: what it printed and how it
%% ended, or the oracle it failed first.
outcome(Text) ->
    try ern_typecheck:check_string(?MODULE_NAMESPACE, Text) of
        {error, Diagnostics} ->
            {refused, [ern_diagnostic:short("", Diagnostic) || Diagnostic <- Diagnostics]};
        {ok, Typed, Interface, Env} ->
            Build = #{source_hash => <<>>, deps => []},
            case catch_all(fun() -> ern_emitter:compile(?MODULE_NAMESPACE, Typed, Interface,
                                                        Env, Build) end) of
                {ok, {ok, ErlangModule, Beam}} -> run(ErlangModule, Beam);
                {crashed, Crash} -> {not_compiled, Crash}
            end
    catch Class:Reason:Trace -> {checker_crashed, Class, Reason, lists:sublist(Trace, 3)}
    end.

run(ErlangModule, Beam) ->
    code:purge(ErlangModule),
    {module, ErlangModule} = code:load_binary(ErlangModule, "generated", Beam),
    Self = self(),
    Tag = make_ref(),
    Collect = fun(Written) -> Self ! {Tag, Written} end,
    Init = fun() ->
                   case erlang:function_exported(ErlangModule, '$init', 0) of
                       true -> ErlangModule:'$init'();
                       false -> ok
                   end
           end,
    Ended = ern_rt:run_main(fun() -> ErlangModule:main() end, <<"main">>,
                            #{init => Init, stdout => Collect, stderr => fun(_) -> ok end,
                              stdin => fun() -> eof end}),
    {Ended, collected(Tag, [])}.

collected(Tag, Acc) ->
    receive
        {Tag, Written} -> collected(Tag, [Written | Acc])
    after 0 ->
        iolist_to_binary(lists:reverse(Acc))
    end.

catch_all(Run) ->
    try {ok, Run()}
    catch Class:Reason:Trace -> {crashed, {Class, Reason, lists:sublist(Trace, 3)}}
    end.

%%
%% The pure round
%%

%% A program of helpers and a value: its text and what its run should be.
pure_program(Size) ->
    Helpers = helpers(Size),
    %% three values, so that more of what the program computes is printed
    Type = {tuple, [any_type(2), any_type(1), any_type(1)]},
    Value = generate(Type, #{vars => [], helpers => Helpers}, Size),
    Text = [?DECLARATIONS, [[helper_text(Helper), "\n\n"] || Helper <- Helpers],
            "fn value() : ", type_text(Type), " =\n    ", expr_text(Value), "\n\n",
            "export fn main() : Unit with m = Io.println(Io.show(value()))\n"],
    Expected = try evaluate(Value, #{}, Helpers) of
                   Result -> {ok, <<(show(Result))/binary, "\n">>}
               catch throw:{fault, Cause} -> {{fault, Cause}, <<>>}
               end,
    {iolist_to_binary(Text), Expected}.

%% A few helper functions, each over the ones before it, and at times one
%% that folds a list of Int by structural recursion.
helpers(Size) ->
    lists:foldl(fun(_, Helpers) ->
                        Name = fresh("h"),
                        Helper = case rand:uniform(3) of
                                     1 -> recursive_helper(Name, Helpers, Size);
                                     _ -> plain_helper(Name, Helpers, Size)
                                 end,
                        Helpers ++ [Helper]
                end, [], lists:seq(1, rand:uniform(3) - 1)).

plain_helper(Name, Helpers, Size) ->
    Params = [{fresh("p"), base_type()} || _ <- lists:seq(1, rand:uniform(3) - 1)],
    Result = base_type(),
    Body = generate(Result, #{vars => Params, helpers => Helpers}, Size),
    {helper, Name, Params, Result, Body}.

%% fn h(xs : List(Int), acc : T) : T =
%%     match xs { [] -> acc | x :: rest -> h(rest, body) }
recursive_helper(Name, Helpers, Size) ->
    Result = base_type(),
    [Xs, Acc, X, Rest] = [fresh("xs"), fresh("acc"), fresh("x"), fresh("rest")],
    Params = [{Xs, {list, int}}, {Acc, Result}],
    Self = {helper, Name, Params, Result, undefined},
    Step = generate(Result, #{vars => [{Acc, Result}, {X, int}], helpers => Helpers}, Size),
    Body = {match, {var, Xs},
            [{{plist, []}, none, {var, Acc}},
             {{pcons, {pvar, X}, {pvar, Rest}}, none,
              {call, {helper, Name}, [{var, Rest}, Step]}}]},
    setelement(5, Self, Body).

%%
%% The process round
%%

%% A program of one of the shapes, its expressions the pure round's.
process_program(Size) ->
    Helpers = helpers(Size),
    Scope = #{vars => [], helpers => Helpers},
    Shape = pick([worker, worker, server, server, timeout, timeout, deadlock]),
    {Body, Expected} = process_shape(Shape, Scope, Helpers, Size),
    Text = [?DECLARATIONS, [[helper_text(Helper), "\n\n"] || Helper <- Helpers], Body],
    {iolist_to_binary(Text), Expected}.

%% A worker spawned to send its value back, which main prints.
process_shape(worker, Scope, Helpers, Size) ->
    Type = any_type(1),
    {Value, Result} = faultless(Type, Scope, Helpers, Size),
    Body = ["type Main = Done(", type_text(Type), ")\n\n",
            "export fn main() : Unit with Main = {\n",
            "    let me = self();\n",
            "    let _ = spawn(fn() = send(me, Done(", expr_text(Value), ")));\n",
            "    receive { Done(value) -> Io.println(Io.show(value)) }\n",
            "}\n"],
    {Body, {ok, <<(show(Result))/binary, "\n">>}};
%% A server that sums what it is sent and answers a call with the sum.
process_shape(server, Scope, Helpers, Size) ->
    Sent = [faultless(int, Scope, Helpers, Size) || _ <- lists:seq(1, rand:uniform(3))],
    Body = ["type Request = Add(Int) | Total(reply : Reply(Int))\n\n",
            "fn serve(total : Int) : Unit with Request =\n",
            "    receive {\n",
            "        Add(amount) -> serve(total + amount)\n",
            "      | Total(reply = reply) -> {\n",
            "            answer(reply, total);\n",
            "            serve(total)\n",
            "        }\n",
            "    }\n\n",
            "export fn main() : Unit with m = {\n",
            "    let server = spawn(fn() = serve(0));\n",
            [["    send(server, Add(", expr_text(Value), "));\n"] || {Value, _} <- Sent],
            "    match Address.call(server, fn(reply) = Total(reply = reply), 5000) {\n",
            "        Some(total) -> Io.println(Io.show(total))\n",
            "      | None -> Io.println(\"no answer\")\n",
            "    }\n",
            "}\n"],
    Total = lists:sum([Result || {_, Result} <- Sent]),
    {Body, {ok, <<(integer_to_binary(Total))/binary, "\n">>}};
%% A receive that nothing answers, whose `after` gives the value.
process_shape(timeout, Scope, Helpers, Size) ->
    Type = any_type(1),
    {Value, Result} = faultless(Type, Scope, Helpers, Size),
    Body = ["type Main = Done(", type_text(Type), ")\n\n",
            "export fn main() : Unit with Main =\n",
            "    receive {\n",
            "        Done(value) -> Io.println(Io.show(value))\n",
            "      | after ", integer_to_list(rand:uniform(5) - 1), " -> {\n",
            "            let late : ", type_text(Type), " = ", expr_text(Value), ";\n",
            "            Io.println(Io.show(late))\n",
            "        }\n",
            "    }\n"],
    {Body, {ok, <<(show(Result))/binary, "\n">>}};
%% A receive that nothing will answer: the entry process's deadlock (§8.6).
process_shape(deadlock, Scope, Helpers, Size) ->
    {Value, _} = faultless(int, Scope, Helpers, Size),
    Body = ["type Main = Done(Int)\n\n",
            "export fn main() : Unit with Main = {\n",
            "    let expected = ", expr_text(Value), ";\n",
            "    receive { Done(value) -> Io.println(Io.show(value == expected)) }\n",
            "}\n"],
    {Body, {{fault, <<"deadlock">>}, <<>>}}.

%% An expression of the type that does not fault, and its value.
faultless(Type, Scope, Helpers, Size) ->
    Expr = generate(Type, Scope, Size),
    try evaluate(Expr, #{}, Helpers) of
        Value -> {Expr, Value}
    catch throw:{fault, _} -> faultless(Type, Scope, Helpers, Size)
    end.

%%
%% Types
%%

%% Int, String, Bool, Unit, List(t), Optional(t), #(t, u), Shape, Point,
%% Box(t): a base type, or one built of them to a depth.
base_type() -> pick([int, int, string, bool]).

any_type(0) ->
    base_type();
any_type(Depth) ->
    case rand:uniform(10) of
        1 -> {list, any_type(Depth - 1)};
        2 -> {optional, any_type(Depth - 1)};
        3 -> {tuple, [any_type(Depth - 1), any_type(Depth - 1)]};
        4 -> shape;
        5 -> point;
        6 -> {box, any_type(Depth - 1)};
        7 -> unit;
        _ -> base_type()
    end.

type_text(int) -> "Int";
type_text(string) -> "String";
type_text(bool) -> "Bool";
type_text(unit) -> "Unit";
type_text(shape) -> "Shape";
type_text(point) -> "Point";
type_text({list, Type}) -> ["List(", type_text(Type), ")"];
type_text({optional, Type}) -> ["Optional(", type_text(Type), ")"];
type_text({box, Type}) -> ["Box(", type_text(Type), ")"];
type_text({tuple, Types}) -> ["#(", lists:join(", ", [type_text(Type) || Type <- Types]), ")"].

%%
%% The generator
%%

%% An expression of Type in Scope, its variables and the helpers it may
%% call, to about Depth: past it a literal or a variable.
generate(Type, Scope, Depth) when Depth =< 0 ->
    leaf(Type, Scope);
generate(Type, Scope, Depth) ->
    Forms = [Form || {Form, Weight} <- forms(Type, Scope), _ <- lists:seq(1, Weight)],
    form(pick(Forms), Type, Scope, Depth - 1).

leaf(Type, #{vars := Vars} = Scope) ->
    case [Name || {Name, VarType} <- Vars, VarType =:= Type] of
        Names when Names =/= [] andalso Type =/= unit -> {var, pick(Names)};
        _ -> literal(Type, Scope)
    end.

%% The forms an expression of Type may take, each with a weight.
forms(Type, #{vars := Vars, helpers := Helpers}) ->
    Common = [{literal, 3}, {'if', 2}, {block, 2}, {match_optional, 1}, {match_list, 1},
              {match_shape, 1}, {match_tuple, 1}, {match_int, 1}, {lambda_call, 1},
              {with_default, 1}, {fold, 1}],
    Var = [{var, 3} || lists:keymember(Type, 2, Vars)],
    Call = [{helper_call, 3} || lists:keymember(Type, 4, Helpers)],
    Local = [{local_call, 3} || lists:any(fun({_, {fn, _, Result}}) -> Result =:= Type;
                                             (_) -> false
                                          end, Vars)],
    Common ++ Var ++ Call ++ Local ++ own_forms(Type).

own_forms(int) ->
    [{arithmetic, 4}, {negation, 1}, {string_size, 1}, {list_size, 1}, {int_call, 1},
     {select_point, 1}, {select_box, 1}];
own_forms(bool) ->
    [{comparison, 3}, {logic, 2}, {'not', 1}, {is_empty, 1}, {is_some, 1}, {contains, 1}];
own_forms(string) ->
    [{concat, 3}, {to_string, 2}, {to_upper, 1}, {repeat, 1}, {select_box, 1}];
own_forms({list, int}) ->
    [{range, 1} | own_forms({list, any})];
own_forms({list, _}) ->
    [{list_literal, 3}, {cons, 2}, {append, 1}, {list_map, 1}, {list_filter, 1},
     {reverse, 1}];
own_forms({optional, _}) ->
    [{some, 3}, {list_get, 1}, {optional_map, 1}];
own_forms(point) ->
    [{update, 2}];
own_forms({box, _}) ->
    [{update, 2}];
own_forms(_) ->
    [].

form(literal, Type, Scope, Depth) -> literal(Type, Scope, Depth);
form(var, Type, #{vars := Vars}, _) ->
    {var, pick([Name || {Name, VarType} <- Vars, VarType =:= Type])};
form('if', Type, Scope, Depth) ->
    {'if', generate(bool, Scope, Depth), generate(Type, Scope, Depth),
     generate(Type, Scope, Depth)};
form(block, Type, Scope, Depth) ->
    %% bindings of the block's own type or of Int, as often as not, which
    %% its body then reads, so that what they compute is seen
    Lets = [{fresh("v"), pick([Type, int, any_type(1)])} || _ <- lists:seq(1, rand:uniform(2))],
    {Bindings, Inner} = lists:mapfoldl(fun({Name, LetType}, Acc) ->
                                               Bound = generate(LetType, Acc, Depth),
                                               {{'let', Name, LetType, Bound},
                                                bind(Acc, Name, LetType)}
                                       end, Scope, Lets),
    case rand:uniform(2) of
        1 ->
            {[{local_fn, Name, Params, _, _}] = Local, Within} = local_fn(Type, Inner, Depth),
            Last = pick([generate(Type, Within, Depth),
                         {call, {local, Name},
                          [generate(ParamType, Within, Depth) || {_, ParamType} <- Params]}]),
            {block, Bindings ++ Local, Last};
        _ ->
            {block, Bindings, generate(Type, Inner, Depth)}
    end;
form(local_call, Type, #{vars := Vars} = Scope, Depth) ->
    Callable = [Var || {_, {fn, _, Result}} = Var <- Vars, Result =:= Type],
    {Name, {fn, ParamTypes, _}} = pick(Callable),
    {call, {local, Name}, [generate(ParamType, Scope, Depth) || ParamType <- ParamTypes]};
form(match_optional, Type, Scope, Depth) ->
    Inner = any_type(1),
    Bound = fresh("y"),
    Some = {{pcon, 'Some', {positional, {pvar, Bound}}}, none,
            generate(Type, bind(Scope, Bound, Inner), Depth)},
    None = {{pcon, 'None', none}, none, generate(Type, Scope, Depth)},
    Guarded = guarded(Inner, Bound, Type, Scope, Depth),
    scrutinized({optional, Inner}, Scope, Depth, Guarded ++ shuffle([Some, None]));
form(match_list, Type, Scope, Depth) ->
    Element = base_type(),
    {Head, Tail} = {fresh("h"), fresh("t")},
    Empty = {{plist, []}, none, generate(Type, Scope, Depth)},
    Cons = {{pcons, {pvar, Head}, {pvar, Tail}}, none,
            generate(Type, bind(bind(Scope, Head, Element), Tail, {list, Element}), Depth)},
    Single = {{plist, [{pvar, Head}]}, none, generate(Type, bind(Scope, Head, Element), Depth)},
    Clauses = case rand:uniform(2) of
                  1 -> [Empty, Cons];
                  _ -> [Single, Empty, {{pwild}, none, generate(Type, Scope, Depth)}]
              end,
    scrutinized({list, Element}, Scope, Depth, Clauses);
form(match_shape, Type, Scope, Depth) ->
    {Radius, Width} = {fresh("r"), fresh("w")},
    Circle = {{pcon, 'Circle', {positional, {pvar, Radius}}}, none,
              generate(Type, bind(Scope, Radius, int), Depth)},
    Rect = case rand:uniform(2) of
               1 -> {{pcon, 'Rect', {named, [{w, {pvar, Width}}]}}, none,
                     generate(Type, bind(Scope, Width, int), Depth)};
               _ -> {{pcon, 'Rect', {named, []}}, none, generate(Type, Scope, Depth)}
           end,
    Dot = {{pcon, 'Dot', none}, none, generate(Type, Scope, Depth)},
    Clauses = case rand:uniform(2) of
                  1 -> shuffle([Circle, Rect, Dot]);
                  _ -> [pick([Circle, Rect, Dot]), {{pwild}, none, generate(Type, Scope, Depth)}]
              end,
    scrutinized(shape, Scope, Depth, Clauses);
form(match_tuple, Type, Scope, Depth) ->
    {First, Second} = {base_type(), base_type()},
    {Left, Right} = {fresh("a"), fresh("b")},
    Inner = bind(bind(Scope, Left, First), Right, Second),
    scrutinized({tuple, [First, Second]}, Scope, Depth,
                [{{ptuple, [{pvar, Left}, {pvar, Right}]}, none, generate(Type, Inner, Depth)}]);
form(match_int, Type, Scope, Depth) ->
    Literals = lists:usort([rand:uniform(7) - 4 || _ <- lists:seq(1, rand:uniform(3))]),
    Clauses = [{{plit, Literal}, none, generate(Type, Scope, Depth)} || Literal <- Literals],
    Bound = fresh("n"),
    Last = {{pvar, Bound}, none, generate(Type, bind(Scope, Bound, int), Depth)},
    scrutinized(int, Scope, Depth, Clauses ++ [Last]);
form(lambda_call, Type, Scope, Depth) ->
    {Param, ParamType} = {fresh("z"), base_type()},
    Body = generate(Type, bind(Scope, Param, ParamType), Depth),
    Lambda = {lambda, [{Param, ParamType}], Type, Body},
    {call, Lambda, [generate(ParamType, Scope, Depth)]};
form(with_default, Type, Scope, Depth) ->
    {call, {qualified, "Optional.withDefault"},
     [generate({optional, Type}, Scope, Depth), generate(Type, Scope, Depth)]};
form(fold, Type, Scope, Depth) ->
    Element = base_type(),
    {Acc, Item} = {fresh("acc"), fresh("e")},
    Step = {lambda, [{Acc, Type}, {Item, Element}], Type,
            generate(Type, bind(bind(Scope, Acc, Type), Item, Element), Depth)},
    {call, {qualified, "List.foldLeft"},
     [generate({list, Element}, Scope, Depth), generate(Type, Scope, Depth), Step]};
form(helper_call, Type, #{helpers := Helpers} = Scope, Depth) ->
    {helper, Name, Params, _, _} = pick([Helper || {helper, _, _, Result, _} = Helper <- Helpers,
                                                  Result =:= Type]),
    {call, {helper, Name}, [generate(ParamType, Scope, Depth) || {_, ParamType} <- Params]};
form(arithmetic, int, Scope, Depth) ->
    {binop, pick(['+', '-', '*', '+', '-', '*', '/', '%']), generate(int, Scope, Depth),
     generate(int, Scope, Depth)};
form(negation, int, Scope, Depth) ->
    {negation, generate(int, Scope, Depth)};
form(string_size, int, Scope, Depth) ->
    {call, {qualified, "String.size"}, [generate(string, Scope, Depth)]};
form(list_size, int, Scope, Depth) ->
    {call, {qualified, "List.size"}, [generate({list, base_type()}, Scope, Depth)]};
form(int_call, int, Scope, Depth) ->
    case rand:uniform(3) of
        1 -> {call, {qualified, "Int.abs"}, [generate(int, Scope, Depth)]};
        2 -> {call, {qualified, "Int.min"}, [generate(int, Scope, Depth) || _ <- [1, 2]]};
        _ -> {call, {qualified, "Int.max"}, [generate(int, Scope, Depth) || _ <- [1, 2]]}
    end;
form(select_point, int, Scope, Depth) ->
    {select, generate(point, Scope, Depth), pick([x, y])};
form(select_box, Type, Scope, Depth) ->
    {select, generate({box, Type}, Scope, Depth), item};
form(comparison, bool, Scope, Depth) ->
    Operand = pick([int, int, string]),
    Operator = case Operand of
                   int -> pick(['<', '<=', '>', '>=', '==', '!=']);
                   string -> pick(['<', '==', '!='])
               end,
    {binop, Operator, generate(Operand, Scope, Depth), generate(Operand, Scope, Depth)};
form(logic, bool, Scope, Depth) ->
    {binop, pick(['&&', '||']), generate(bool, Scope, Depth), generate(bool, Scope, Depth)};
form('not', bool, Scope, Depth) ->
    {'not', generate(bool, Scope, Depth)};
form(is_empty, bool, Scope, Depth) ->
    {call, {qualified, "List.isEmpty"}, [generate({list, base_type()}, Scope, Depth)]};
form(is_some, bool, Scope, Depth) ->
    {call, {qualified, "Optional.isSome"}, [generate({optional, base_type()}, Scope, Depth)]};
form(contains, bool, Scope, Depth) ->
    {call, {qualified, "String.contains"},
     [generate(string, Scope, Depth), generate(string, Scope, Depth)]};
form(concat, string, Scope, Depth) ->
    {binop, '<>', generate(string, Scope, Depth), generate(string, Scope, Depth)};
form(to_string, string, Scope, Depth) ->
    {call, {qualified, "Int.toString"}, [generate(int, Scope, Depth)]};
form(to_upper, string, Scope, Depth) ->
    {call, {qualified, "String.toUpper"}, [generate(string, Scope, Depth)]};
form(repeat, string, Scope, Depth) ->
    {call, {qualified, "String.repeat"},
     [generate(string, Scope, Depth), {int, rand:uniform(5) - 2}]};
form(list_literal, {list, Element}, Scope, Depth) ->
    {list, [generate(Element, Scope, Depth) || _ <- lists:seq(1, rand:uniform(4) - 1)]};
form(cons, {list, Element}, Scope, Depth) ->
    {binop, '::', generate(Element, Scope, Depth), generate({list, Element}, Scope, Depth)};
form(append, {list, _} = Type, Scope, Depth) ->
    {binop, '<>', generate(Type, Scope, Depth), generate(Type, Scope, Depth)};
form(list_map, {list, Element}, Scope, Depth) ->
    {From, Item} = {base_type(), fresh("e")},
    Function = {lambda, [{Item, From}], Element,
                generate(Element, bind(Scope, Item, From), Depth)},
    {call, {qualified, "List.map"}, [generate({list, From}, Scope, Depth), Function]};
form(list_filter, {list, Element} = Type, Scope, Depth) ->
    Item = fresh("e"),
    Keep = {lambda, [{Item, Element}], bool, generate(bool, bind(Scope, Item, Element), Depth)},
    {call, {qualified, "List.filter"}, [generate(Type, Scope, Depth), Keep]};
form(reverse, {list, _} = Type, Scope, Depth) ->
    {call, {qualified, "List.reverse"}, [generate(Type, Scope, Depth)]};
form(range, {list, int}, _, _) ->
    {call, {qualified, "List.range"}, [{int, rand:uniform(7) - 4}, {int, rand:uniform(7) - 2}]};
form(some, {optional, Inner}, Scope, Depth) ->
    {con, 'Some', {positional, generate(Inner, Scope, Depth)}};
form(list_get, {optional, Inner}, Scope, Depth) ->
    {call, {qualified, "List.get"},
     [generate({list, Inner}, Scope, Depth), generate(int, Scope, Depth)]};
form(optional_map, {optional, Inner}, Scope, Depth) ->
    {From, Item} = {base_type(), fresh("e")},
    Function = {lambda, [{Item, From}], Inner, generate(Inner, bind(Scope, Item, From), Depth)},
    {call, {qualified, "Optional.map"}, [generate({optional, From}, Scope, Depth), Function]};
form(update, point, Scope, Depth) ->
    {update, 'Point', generate(point, Scope, Depth), [{pick([x, y]), generate(int, Scope, Depth)}]};
form(update, {box, Inner} = Type, Scope, Depth) ->
    {update, 'Box', generate(Type, Scope, Depth), [{item, generate(Inner, Scope, Depth)}]}.

%% A local fn of the block's type declared after its bindings, which its
%% body sees and the block's last expression may call (report §5.4).
local_fn(Type, Scope, Depth) ->
    Name = fresh("g"),
    Params = [{fresh("q"), base_type()} || _ <- lists:seq(1, rand:uniform(2))],
    Result = Type,
    Inner = lists:foldl(fun({Param, ParamType}, Acc) -> bind(Acc, Param, ParamType) end,
                        Scope, Params),
    Body = generate(Result, Inner, Depth - 1),
    {[{local_fn, Name, Params, Result, Body}],
     bind(Scope, Name, {fn, [ParamType || {_, ParamType} <- Params], Result})}.

%% A match of the clauses over an expression of Type, bound first by a
%% `let` that writes its type, so that the variables its patterns bind have
%% that type though the expression alone does not fix it, `None` or `[]`
%% (report §4.8: an operator's operand type is known).
scrutinized(Type, Scope, Depth, Clauses) ->
    Name = fresh("s"),
    {block, [{'let', Name, Type, generate(Type, Scope, Depth)}], {match, {var, Name}, Clauses}}.

%% At times a guarded clause before a match's others, which guards leave
%% to cover the type (§5.9): `Some(y) when y == ...`.
guarded(int, Bound, Type, Scope, Depth) ->
    case rand:uniform(3) of
        1 ->
            Inner = bind(Scope, Bound, int),
            Guard = {binop, '>', {var, Bound}, generate(int, Inner, 1)},
            [{{pcon, 'Some', {positional, {pvar, Bound}}}, Guard, generate(Type, Inner, Depth)}];
        _ -> []
    end;
guarded(_, _, _, _, _) ->
    [].

literal(Type, Scope) ->
    literal(Type, Scope, 0).

literal(int, _, _) ->
    {int, pick([0, 1, 2, 7, -3, rand:uniform(201) - 101, rand:uniform(1 bsl 70)])};
literal(string, _, _) ->
    {string, list_to_binary([pick("ab yz09") || _ <- lists:seq(1, rand:uniform(5) - 1)])};
literal(bool, _, _) -> {bool, pick([true, false])};
literal(unit, _, _) -> unit;
literal({list, Element}, Scope, Depth) ->
    {list, [generate(Element, Scope, Depth - 1) || _ <- lists:seq(1, rand:uniform(3) - 1)]};
literal({optional, Inner}, Scope, Depth) ->
    pick([{con, 'None', none}, {con, 'Some', {positional, generate(Inner, Scope, Depth - 1)}}]);
literal({tuple, Types}, Scope, Depth) ->
    {tuple, [generate(Type, Scope, Depth - 1) || Type <- Types]};
literal(shape, Scope, Depth) ->
    pick([{con, 'Circle', {positional, generate(int, Scope, Depth - 1)}},
          {con, 'Rect', {named, [{w, generate(int, Scope, Depth - 1)},
                                 {h, generate(int, Scope, Depth - 1)}]}},
          {con, 'Dot', none}]);
literal(point, Scope, Depth) ->
    {con, 'Point', {named, [{x, generate(int, Scope, Depth - 1)},
                            {y, generate(int, Scope, Depth - 1)}]}};
literal({box, Inner}, Scope, Depth) ->
    {con, 'Box', {named, [{item, generate(Inner, Scope, Depth - 1)}]}}.

bind(#{vars := Vars} = Scope, Name, Type) ->
    Scope#{vars => [{Name, Type} | Vars]}.

fresh(Prefix) ->
    Next = get(fresh) + 1,
    put(fresh, Next),
    Prefix ++ integer_to_list(Next).

pick(Choices) ->
    lists:nth(rand:uniform(length(Choices)), Choices).

shuffle(List) ->
    [Element || {_, Element} <- lists:sort([{rand:uniform(), Element} || Element <- List])].

%%
%% The program as text
%%

helper_text({helper, Name, Params, Result, Body}) ->
    ["fn ", Name, "(", params_text(Params), ") : ", type_text(Result), " =\n    ",
     expr_text(Body)].

params_text(Params) ->
    lists:join(", ", [[Param, " : ", type_text(Type)] || {Param, Type} <- Params]).

expr_text({int, Int}) when Int >= 0 -> integer_to_list(Int);
expr_text({int, Int}) -> ["(-", integer_to_list(-Int), ")"];
expr_text({string, Text}) -> [$", Text, $"];
expr_text({bool, Bool}) -> atom_to_list(Bool);
expr_text(unit) -> "Unit";
expr_text({var, Name}) -> Name;
expr_text({binop, Operator, Left, Right}) ->
    ["(", expr_text(Left), " ", atom_to_list(Operator), " ", expr_text(Right), ")"];
expr_text({negation, Operand}) -> ["(-", expr_text(Operand), ")"];
expr_text({'not', Operand}) -> ["(!", expr_text(Operand), ")"];
expr_text({'if', Condition, Then, Else}) ->
    ["(if ", expr_text(Condition), " then ", expr_text(Then), " else ", expr_text(Else), ")"];
expr_text({block, Statements, Body}) ->
    ["{ ", [[statement_text(Statement), "; "] || Statement <- Statements], expr_text(Body), " }"];
expr_text({match, Scrutinee, Clauses}) ->
    ["(match ", expr_text(Scrutinee), " { ",
     lists:join(" | ", [clause_text(Clause) || Clause <- Clauses]), " })"];
expr_text({con, Name, none}) -> atom_to_list(Name);
expr_text({con, Name, {positional, Arg}}) -> [atom_to_list(Name), "(", expr_text(Arg), ")"];
expr_text({con, Name, {named, Fields}}) ->
    [atom_to_list(Name), "(", fields_text(Fields), ")"];
expr_text({tuple, Elements}) -> ["#(", lists:join(", ", [expr_text(E) || E <- Elements]), ")"];
expr_text({list, Elements}) -> ["[", lists:join(", ", [expr_text(E) || E <- Elements]), "]"];
expr_text({select, Record, Field}) -> ["(", expr_text(Record), ").", atom_to_list(Field)];
expr_text({update, Name, Base, Fields}) ->
    [atom_to_list(Name), "(..", expr_text(Base), ", ", fields_text(Fields), ")"];
expr_text({lambda, Params, Result, Body}) ->
    ["(fn(", params_text(Params), ") : ", type_text(Result), " = ", expr_text(Body), ")"];
expr_text({call, {qualified, Name}, Args}) -> [Name, "(", args_text(Args), ")"];
expr_text({call, {helper, Name}, Args}) -> [Name, "(", args_text(Args), ")"];
expr_text({call, {local, Name}, Args}) -> [Name, "(", args_text(Args), ")"];
expr_text({call, Callee, Args}) -> [expr_text(Callee), "(", args_text(Args), ")"].

args_text(Args) -> lists:join(", ", [expr_text(Arg) || Arg <- Args]).

statement_text({'let', Name, Type, Bound}) ->
    ["let ", Name, " : ", type_text(Type), " = ", expr_text(Bound)];
statement_text({local_fn, Name, Params, Result, Body}) ->
    ["fn ", Name, "(", params_text(Params), ") : ", type_text(Result), " = ", expr_text(Body)].

fields_text(Fields) ->
    lists:join(", ", [[atom_to_list(Field), " = ", expr_text(Value)] || {Field, Value} <- Fields]).

clause_text({Pattern, none, Body}) -> [pattern_text(Pattern), " -> ", expr_text(Body)];
clause_text({Pattern, Guard, Body}) ->
    [pattern_text(Pattern), " when ", expr_text(Guard), " -> ", expr_text(Body)].

pattern_text({pwild}) -> "_";
pattern_text({pvar, Name}) -> Name;
pattern_text({plit, Int}) -> integer_to_list(Int);
pattern_text({pcon, Name, none}) -> atom_to_list(Name);
pattern_text({pcon, Name, {positional, Pattern}}) ->
    [atom_to_list(Name), "(", pattern_text(Pattern), ")"];
pattern_text({pcon, Name, {named, Fields}}) ->
    [atom_to_list(Name), "(",
     lists:join(", ", [[atom_to_list(Field), " = ", pattern_text(Pattern)]
                       || {Field, Pattern} <- Fields]), ")"];
pattern_text({ptuple, Patterns}) ->
    ["#(", lists:join(", ", [pattern_text(Pattern) || Pattern <- Patterns]), ")"];
pattern_text({plist, Patterns}) ->
    ["[", lists:join(", ", [pattern_text(Pattern) || Pattern <- Patterns]), "]"];
pattern_text({pcons, Head, Tail}) -> [pattern_text(Head), " :: ", pattern_text(Tail)].

%%
%% The interpreter: the program's value by the report's rules, a value an
%% Erlang term, a constructor `{con, Name, Fields}` and a closure
%% `{closure, Params, Body, Env}`; a fault thrown as `{fault, Cause}`
%%

evaluate({int, Int}, _, _) -> Int;
evaluate({string, Text}, _, _) -> Text;
evaluate({bool, Bool}, _, _) -> Bool;
evaluate(unit, _, _) -> unit;
evaluate({var, Name}, Env, _) -> maps:get(Name, Env);
%% report §4.8: `&&` and `||` short-circuit
evaluate({binop, '&&', Left, Right}, Env, Helpers) ->
    evaluate(Left, Env, Helpers) andalso evaluate(Right, Env, Helpers);
evaluate({binop, '||', Left, Right}, Env, Helpers) ->
    evaluate(Left, Env, Helpers) orelse evaluate(Right, Env, Helpers);
%% report §5.1: the left operand first
evaluate({binop, Operator, Left, Right}, Env, Helpers) ->
    LeftValue = evaluate(Left, Env, Helpers),
    operate(Operator, LeftValue, evaluate(Right, Env, Helpers));
evaluate({negation, Operand}, Env, Helpers) -> -evaluate(Operand, Env, Helpers);
evaluate({'not', Operand}, Env, Helpers) -> not evaluate(Operand, Env, Helpers);
evaluate({'if', Condition, Then, Else}, Env, Helpers) ->
    case evaluate(Condition, Env, Helpers) of
        true -> evaluate(Then, Env, Helpers);
        false -> evaluate(Else, Env, Helpers)
    end;
%% report §5.4: `let`s in order; a local fn sees the bindings before it
evaluate({block, Statements, Body}, Env, Helpers) ->
    Bind = fun({'let', Name, _, Bound}, Acc) -> Acc#{Name => evaluate(Bound, Acc, Helpers)};
              ({local_fn, Name, Params, _, FnBody}, Acc) ->
                   Acc#{Name => {closure, Params, FnBody, Acc}}
           end,
    evaluate(Body, lists:foldl(Bind, Env, Statements), Helpers);
evaluate({match, Scrutinee, Clauses}, Env, Helpers) ->
    clause(evaluate(Scrutinee, Env, Helpers), Clauses, Env, Helpers);
evaluate({con, Name, none}, _, _) -> {con, Name, none};
evaluate({con, Name, {positional, Arg}}, Env, Helpers) ->
    {con, Name, {positional, evaluate(Arg, Env, Helpers)}};
evaluate({con, Name, {named, Fields}}, Env, Helpers) ->
    {con, Name, {named, [{Field, evaluate(Value, Env, Helpers)} || {Field, Value} <- Fields]}};
evaluate({tuple, Elements}, Env, Helpers) -> {tuple, [evaluate(E, Env, Helpers) || E <- Elements]};
evaluate({list, Elements}, Env, Helpers) -> [evaluate(E, Env, Helpers) || E <- Elements];
evaluate({select, Record, Field}, Env, Helpers) ->
    {con, _, {named, Fields}} = evaluate(Record, Env, Helpers),
    proplists:get_value(Field, Fields);
%% report §5.6: the base first, then the fields in source order
evaluate({update, Name, Base, Updates}, Env, Helpers) ->
    {con, Name, {named, Fields}} = evaluate(Base, Env, Helpers),
    New = [{Field, evaluate(Value, Env, Helpers)} || {Field, Value} <- Updates],
    {con, Name, {named, [{Field, proplists:get_value(Field, New, Old)} || {Field, Old} <- Fields]}};
evaluate({lambda, Params, _, Body}, Env, _) -> {closure, Params, Body, Env};
evaluate({call, Callee, Args}, Env, Helpers) ->
    Values = [evaluate(Arg, Env, Helpers) || Arg <- Args],
    apply_callee(Callee, Values, Env, Helpers).

apply_callee({qualified, Name}, Values, _, Helpers) ->
    library(Name, Values, Helpers);
apply_callee({local, Name}, Values, Env, Helpers) ->
    apply_closure(maps:get(Name, Env), Values, Helpers);
apply_callee({helper, Name}, Values, _, Helpers) ->
    {helper, Name, Params, _, Body} = lists:keyfind(Name, 2, Helpers),
    evaluate(Body, maps:from_list(lists:zip([Param || {Param, _} <- Params], Values)), Helpers);
apply_callee(Lambda, Values, Env, Helpers) ->
    apply_closure(evaluate(Lambda, Env, Helpers), Values, Helpers).

apply_closure({closure, Params, Body, Captured}, Values, Helpers) ->
    Bound = maps:from_list(lists:zip([Param || {Param, _} <- Params], Values)),
    evaluate(Body, maps:merge(Captured, Bound), Helpers).

%% report §3.1, §4.8: `/` truncates toward zero, `%` takes the sign of the
%% first, and either by zero faults (§7.4)
operate('+', Left, Right) -> Left + Right;
operate('-', Left, Right) -> Left - Right;
operate('*', Left, Right) -> Left * Right;
operate('/', _, 0) -> throw({fault, <<"division by zero">>});
operate('/', Left, Right) -> Left div Right;
operate('%', _, 0) -> throw({fault, <<"division by zero">>});
operate('%', Left, Right) -> Left rem Right;
operate('<>', Left, Right) when is_binary(Left) -> <<Left/binary, Right/binary>>;
operate('<>', Left, Right) -> Left ++ Right;
operate('::', Head, Tail) -> [Head | Tail];
operate('==', Left, Right) -> Left =:= Right;
operate('!=', Left, Right) -> Left =/= Right;
operate('<', Left, Right) -> Left < Right;
operate('<=', Left, Right) -> Left =< Right;
operate('>', Left, Right) -> Left > Right;
operate('>=', Left, Right) -> Left >= Right.

%% The first clause whose pattern matches and whose guard holds (§5.9).
clause(Value, [{Pattern, Guard, Body} | Rest], Env, Helpers) ->
    case matched(Pattern, Value, Env) of
        {true, Bound} ->
            case Guard =:= none orelse evaluate(Guard, Bound, Helpers) of
                true -> evaluate(Body, Bound, Helpers);
                false -> clause(Value, Rest, Env, Helpers)
            end;
        false ->
            clause(Value, Rest, Env, Helpers)
    end.

matched({pwild}, _, Env) -> {true, Env};
matched({pvar, Name}, Value, Env) -> {true, Env#{Name => Value}};
matched({plit, Int}, Int, Env) -> {true, Env};
matched({pcon, Name, none}, {con, Name, none}, Env) -> {true, Env};
matched({pcon, Name, {positional, Pattern}}, {con, Name, {positional, Value}}, Env) ->
    matched(Pattern, Value, Env);
matched({pcon, Name, {named, Patterns}}, {con, Name, {named, Fields}}, Env) ->
    all_matched([{Pattern, proplists:get_value(Field, Fields)} || {Field, Pattern} <- Patterns],
                Env);
matched({ptuple, Patterns}, {tuple, Values}, Env) ->
    all_matched(lists:zip(Patterns, Values), Env);
matched({plist, Patterns}, Values, Env) when length(Patterns) =:= length(Values) ->
    all_matched(lists:zip(Patterns, Values), Env);
matched({pcons, Head, Tail}, [Value | Values], Env) ->
    all_matched([{Head, Value}, {Tail, Values}], Env);
matched(_, _, _) -> false.

all_matched([], Env) -> {true, Env};
all_matched([{Pattern, Value} | Rest], Env) ->
    case matched(Pattern, Value, Env) of
        {true, Bound} -> all_matched(Rest, Bound);
        false -> false
    end.

%% The library functions the programs call, by their sections of Appendix E.
library("Optional.withDefault", [{con, 'Some', {positional, Value}}, _], _) -> Value;
library("Optional.withDefault", [_, Default], _) -> Default;
library("Optional.isSome", [Value], _) -> Value =/= {con, 'None', none};
library("Optional.map", [{con, 'Some', {positional, Value}}, Function], Helpers) ->
    {con, 'Some', {positional, apply_closure(Function, [Value], Helpers)}};
library("Optional.map", [None, _], _) -> None;
library("List.foldLeft", [List, Initial, Step], Helpers) ->
    lists:foldl(fun(Element, Acc) -> apply_closure(Step, [Acc, Element], Helpers) end,
                Initial, List);
library("List.map", [List, Function], Helpers) ->
    [apply_closure(Function, [Element], Helpers) || Element <- List];
library("List.filter", [List, Keep], Helpers) ->
    [Element || Element <- List, apply_closure(Keep, [Element], Helpers)];
library("List.size", [List], _) -> length(List);
library("List.isEmpty", [List], _) -> List =:= [];
library("List.reverse", [List], _) -> lists:reverse(List);
library("List.range", [From, To], _) when From > To -> [];
library("List.range", [From, To], _) -> lists:seq(From, To);
library("List.get", [List, Index], _) when Index >= 0, Index < length(List) ->
    {con, 'Some', {positional, lists:nth(Index + 1, List)}};
library("List.get", _, _) -> {con, 'None', none};
library("String.size", [Text], _) -> byte_size(Text);
library("String.contains", [Text, Part], _) ->
    Part =:= <<>> orelse binary:match(Text, Part) =/= nomatch;
library("String.toUpper", [Text], _) -> string:uppercase(Text);
library("String.repeat", [Text, Count], _) -> binary:copy(Text, max(Count, 0));
library("Int.toString", [Int], _) -> integer_to_binary(Int);
library("Int.abs", [Int], _) -> abs(Int);
library("Int.min", [First, Second], _) -> min(First, Second);
library("Int.max", [First, Second], _) -> max(First, Second).

%% What `Io.show` writes for a value (Appendix E.1).
show(Int) when is_integer(Int) -> integer_to_binary(Int);
show(Text) when is_binary(Text) -> <<$", Text/binary, $">>;
show(true) -> <<"true">>;
show(false) -> <<"false">>;
show(unit) -> <<"Unit">>;
show(List) when is_list(List) -> iolist_to_binary(["[", shown(List), "]"]);
show({tuple, Values}) -> iolist_to_binary(["#(", shown(Values), ")"]);
show({con, Name, none}) -> atom_to_binary(Name);
show({con, Name, {positional, Value}}) ->
    iolist_to_binary([atom_to_list(Name), "(", show(Value), ")"]);
show({con, Name, {named, Fields}}) ->
    iolist_to_binary([atom_to_list(Name), "(",
                      lists:join(", ", [[atom_to_list(Field), " = ", show(Value)]
                                        || {Field, Value} <- Fields]), ")"]).

shown(Values) ->
    lists:join(", ", [show(Value) || Value <- Values]).
