#!/usr/bin/env escript
%% -*- erlang -*-
%% Report Appendix E.16: writes the table `Terminal.width` reads into
%% stdlib/terminal.ern, between its two marker lines, from Unicode's data
%% of the version the host's grapheme segmentation follows. Run by
%% `make unicode UC_SPEC=dir`, dir holding EastAsianWidth.txt,
%% emoji-data.txt and UnicodeData.txt, as OTP's lib/stdlib/uc_spec does.
%%
%% A code point is Zero when it is a combining mark (Mn, Me), a format
%% character (Cf) or a control (Cc); else Wide when it is East Asian Wide
%% or Fullwidth or of emoji presentation; else Pictographic when it is
%% extended pictographic; and any other counts one and is not listed.

-define(TERMINAL, "stdlib/terminal.ern").
-define(BEGIN, "// Generated by tools/unicode_width.escript").
-define(END, "// End of the generated table.").

main([Dir]) ->
    {Major, Minor} = unicode_util:spec_version(),
    %% the data must be the version the host segments graphemes by
    {ok, Head} = file:read_file(filename:join(Dir, "EastAsianWidth.txt")),
    Wanted = io_lib:format("EastAsianWidth-~B.~B.", [Major, Minor]),
    case string:find(Head, Wanted) of
        nomatch ->
            io:format(standard_error, "the data in ~s is not Unicode ~B.~B, the host's~n",
                      [Dir, Major, Minor]),
            halt(1);
        _ ->
            ok
    end,
    Zero = categories(filename:join(Dir, "UnicodeData.txt"), ["Mn", "Me", "Cf", "Cc"]),
    Wide = properties(filename:join(Dir, "EastAsianWidth.txt"), ["W", "F"])
        ++ properties(filename:join(Dir, "emoji-data.txt"), ["Emoji_Presentation"]),
    Pictographic = properties(filename:join(Dir, "emoji-data.txt"), ["Extended_Pictographic"]),
    Classes = lists:foldl(fun({Class, Ranges}, Acc) -> mark(Ranges, Class, Acc) end, #{},
                          [{'Pictographic', Pictographic}, {'Wide', Wide}, {'Zero', Zero}]),
    Table = runs(lists:sort(maps:to_list(Classes))),
    Version = io_lib:format("~B.~B", [Major, Minor]),
    Lines = [?BEGIN ++ " from Unicode " ++ Version ++ "'s data, under the Unicode",
             "// License v3 (THIRD_PARTY_LICENSES); not edited by hand."]
        ++ rows([io_lib:format("#(0x~s, 0x~s, ~s)", [code(Lo), code(Hi), Class])
                 || {Lo, Hi, Class} <- Table])
        ++ [?END],
    {ok, Source} = file:read_file(?TERMINAL),
    [Before, Rest] = string:split(Source, ?BEGIN),
    [_, After] = string:split(Rest, ?END),
    Text = [Before, lists:join("\n", Lines), After],
    ok = file:write_file(?TERMINAL, Text),
    io:format("~B ranges from Unicode ~s~n", [length(Table), Version]);
main(_) ->
    io:format(standard_error, "usage: unicode_width.escript uc_spec_dir~n", []),
    halt(1).

%% The code points of the given general categories, from UnicodeData.txt,
%% whose large ranges are a First and a Last line.
categories(File, Wanted) ->
    {ok, Bin} = file:read_file(File),
    Fields = [string:split(L, ";", all) || L <- string:split(Bin, "\n", all), L =/= <<>>],
    ranges([{hex(Code), binary_to_list(Name), binary_to_list(Cat)}
            || [Code, Name, Cat | _] <- Fields, lists:member(binary_to_list(Cat), Wanted)]).

ranges([]) -> [];
ranges([{Lo, Name, _}, {Hi, _, _} | Rest]) ->
    case lists:suffix(", First>", Name) of
        true -> [{Lo, Hi} | ranges(Rest)];
        false -> [{Lo, Lo} | ranges([{Hi, "", ""} | Rest])]
    end;
ranges([{Lo, _, _}]) -> [{Lo, Lo}].

%% The code points with one of the given values, from a file of lines
%% `code[..code] ; value # comment`.
properties(File, Wanted) ->
    {ok, Bin} = file:read_file(File),
    lists:append([range(string:trim(Codes))
                  || Line <- string:split(Bin, "\n", all),
                     [Data | _] <- [string:split(Line, "#")],
                     [Codes, Value] <- [string:split(Data, ";")],
                     lists:member(binary_to_list(string:trim(Value)), Wanted)]).

range(Codes) ->
    case string:split(Codes, "..") of
        [Lo, Hi] -> [{hex(Lo), hex(Hi)}];
        [Code] -> [{hex(Code), hex(Code)}]
    end.

hex(Text) -> binary_to_integer(string:trim(Text), 16).

%% A code point in hexadecimal, at least four digits, as Unicode writes it.
code(C) ->
    Hex = integer_to_list(C, 16),
    lists:duplicate(max(0, 4 - length(Hex)), $0) ++ Hex.

%% Each code point of the ranges given the class, over what an earlier
%% class gave it: the later class wins.
mark(Ranges, Class, Acc) ->
    lists:foldl(fun({Lo, Hi}, A) ->
                    lists:foldl(fun(C, A1) -> A1#{C => Class} end, A, lists:seq(Lo, Hi))
                end, Acc, Ranges).

%% Adjacent code points of one class as one range.
runs([]) -> [];
runs([{C, Class} | Rest]) -> runs(Rest, C, C, Class).

runs([{C, Class} | Rest], Lo, Hi, Class) when C =:= Hi + 1 -> runs(Rest, Lo, C, Class);
runs([{C, Class} | Rest], Lo, Hi, Last) -> [{Lo, Hi, Last} | runs(Rest, C, C, Class)];
runs([], Lo, Hi, Class) -> [{Lo, Hi, Class}].

%% The entries as many to a line as fit in 100 characters, each line a
%% step in (docs/style.md).
%% The table as ern format lays it out (report §11.6): too long for one
%% line, so an entry a line, each under the first.
rows(Entries) ->
    Open = "let widthTable = [",
    Pad = lists:duplicate(length(Open), $\s),
    [First | Rest] = [lists:flatten(E) || E <- Entries],
    [Open ++ First ++ "," | [Pad ++ E ++ "," || E <- lists:droplast(Rest)]]
        ++ [Pad ++ lists:last(Rest) ++ "]"].
